apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      name: web
  replicas: 1 
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - name: web-app
        image: alicankayikci/polilies:web
        envFrom:
        - configMapRef:
            name: cmforall
        - secretRef:
            name: secret-for-all
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 500Mi
            cpu: 100m
          requests:
            memory: 250Mi
            cpu: 80m
        