version: "3.7"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: R1234r
            MYSQL_DATABASE: bookstore_db
            MYSQL_USER: team
            MYSQL_PASSWORD: Roger717*.
        networks:
            - polinet
    myapp:
        build: .
        restart: always
        depends_on:
            - database
        ports:
            - "80:80"
        networks:
            - polinet
        volumes:
            - /var/opt/my_website/dist:/usr/share/nginx/html:ro

networks:
    polinet:
        driver: bridge